data:
  url: "https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data"
  outputfile: "data/raw/abalone.data"

preprocess:
  inputfile: "data/raw/abalone.data"
  out_dir: "data/processed"

eda:
  data_path: "data/processed/train.csv"
  out_dir: "results/eda"
  
model:
  train:
      data_file: "data/processed/train.csv"
      out_dir: "results/model"
  test:
      data_file: "data/processed/test.csv"
      out_dir: "results/model"